#!/bin/sh
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

if [ -s ~/.Xmod_right ]; then
	    xmodmap ~/.Xmod_right
fi

if [ -s ~/.Xresources ]; then
	xrdb ~/.Xresources
fi

xcape -e 'Control_L=Escape'
#urxvtd --quiet --opendisplay --fork
unclutter &
mpd &
dunst -config $DOTFILES/misc/dunst.conf	&
redshift -l 40.6:22.9 -t 6500:3500 &
exec i3
