#!/bin/sh
# pufimg - puf download images (puf is a wget-like util, downloading parallely)

orig=$1
var=${orig%.jpg}
var=$(echo "$var" | grep -o "[0-9][0-9]$")

cutten=${orig%[0-9][0-9].jpg}

for i in $(seq 1 $var) ; do
      echo $cutten$i.jpg
      done | puf -i -
