# Defines environment variables.

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

export DOTFILES="$HOME"/.dotfiles

export BROWSER=qutebrowser

export QT_QPA_PLATFORMTHEME="qt5ct"

export EDITOR=vim
export VISUAL=vim
export PAGER=less

if [[ -z "$LANG" ]]; then
  export LANG=en_US.UTF-8
fi

export WINEARCH=win32
export WINEDEBUG="-all"
export WINEPREFIX=/data/disk0/ksardas/wine
export SDL_AUDIODRIVER="pulse" # XXX why did I set this in the first place
export WINEDLLOVERRIDES="winemenubuilder.exe,mscoree,mshtml=d"
export VDPAU_DRIVER=va_gl
export STEAM_RUNTIME=0
